In [1]:
import numpy as np

In [2]:
l=[2,4,56,422,32,1]
l

[2, 4, 56, 422, 32, 1]

In [3]:
l1=np.array(l)
l1

array([  2,   4,  56, 422,  32,   1])

In [4]:
l1=np.array([2,4,56,422,32,1])
l1

array([  2,   4,  56, 422,  32,   1])

In [5]:
type(l)

list

In [6]:
type(l1)

numpy.ndarray

In [7]:
print(l)
print(l1)

[2, 4, 56, 422, 32, 1]
[  2   4  56 422  32   1]


In [8]:
a=[45,34,22,2]
b=[24,55,3,22]
new=np.array([a,b])
new

array([[45, 34, 22,  2],
       [24, 55,  3, 22]])

In [9]:
new=np.array([45,34,22,2],[24,55,3,22])
new

TypeError: Field elements must be 2- or 3-tuples, got '24'

In [90]:
new=np.array([[45,34,22,2],[24,55,3,22]])
new

array([[45, 34, 22,  2],
       [24, 55,  3, 22]])

In [92]:
a=[45,34,22,2]
b=[24,55,3,22]
new=np.array([[a],[b]])
new

array([[[45, 34, 22,  2]],

       [[24, 55,  3, 22]]])

In [94]:
a=[45,34,22,2]
b=[24,55,3,22]
new=np.array([a],[b])
new

TypeError: Field elements must be 2- or 3-tuples, got '[24, 55, 3, 22]'

In [96]:
a=[2,3,33,4,45]
b=[23,45,56,66,2]
c=[357,523,32,24,2]
d=[32,32,44,333,234]
s=np.array([[a],[b],[c],[d]])
s

array([[[  2,   3,  33,   4,  45]],

       [[ 23,  45,  56,  66,   2]],

       [[357, 523,  32,  24,   2]],

       [[ 32,  32,  44, 333, 234]]])

In [98]:
a=[2,3,33,4,45]
b=[23,45,56,66,2]
c=[357,523,32,24,2]
d=[32,32,44,333,234]
s=np.array([[a,b,c,d]])
s

array([[[  2,   3,  33,   4,  45],
        [ 23,  45,  56,  66,   2],
        [357, 523,  32,  24,   2],
        [ 32,  32,  44, 333, 234]]])

# dtype

In [101]:
np.array([a],dtype=float)

array([[ 2.,  3., 33.,  4., 45.]])

In [103]:
np.array([c],dtype=bool)

array([[ True,  True,  True,  True,  True]])

In [104]:
np.array([b],dtype=complex)

array([[23.+0.j, 45.+0.j, 56.+0.j, 66.+0.j,  2.+0.j]])

In [107]:
np.array([d],dtype=int)

array([[ 32,  32,  44, 333, 234]])

# Numpy Arrays Vs Python Sequences

## arange

In [111]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [113]:
np.arange(1,25,4)

array([ 1,  5,  9, 13, 17, 21])

## reshape

In [116]:
np.arange(1,11).reshape(5,2)
#convert 5 rows and 2 columns from 1 to 11

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [118]:
np.arange(1,11).reshape(2,5)
#convert 2 rows and 5 columns from 1 to 11

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [120]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## ones & zeros

In [123]:
np.ones((1,2))

array([[1., 1.]])

In [125]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [127]:
np.zeros((1,2))

array([[0., 0.]])

In [129]:
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [131]:
np.ones(5)

array([1., 1., 1., 1., 1.])

## random

In [134]:
np.random.random((4,3))

array([[0.43631398, 0.73447386, 0.68441132],
       [0.28685545, 0.180044  , 0.12855784],
       [0.24094274, 0.52090879, 0.47344478],
       [0.16041813, 0.11682516, 0.98432565]])

In [136]:
np.random.rand(3,4)

array([[0.49475067, 0.9956699 , 0.11561348, 0.96780324],
       [0.68881013, 0.52314469, 0.89406957, 0.31646465],
       [0.10229489, 0.39739764, 0.11802354, 0.95537554]])

In [138]:
np.random.randint(3,4)

3

## linspace

linearly space:- linearly separable in a given range at equal distance it creates points

In [141]:
np.linspace(-10,10)

array([-10.        ,  -9.59183673,  -9.18367347,  -8.7755102 ,
        -8.36734694,  -7.95918367,  -7.55102041,  -7.14285714,
        -6.73469388,  -6.32653061,  -5.91836735,  -5.51020408,
        -5.10204082,  -4.69387755,  -4.28571429,  -3.87755102,
        -3.46938776,  -3.06122449,  -2.65306122,  -2.24489796,
        -1.83673469,  -1.42857143,  -1.02040816,  -0.6122449 ,
        -0.20408163,   0.20408163,   0.6122449 ,   1.02040816,
         1.42857143,   1.83673469,   2.24489796,   2.65306122,
         3.06122449,   3.46938776,   3.87755102,   4.28571429,
         4.69387755,   5.10204082,   5.51020408,   5.91836735,
         6.32653061,   6.73469388,   7.14285714,   7.55102041,
         7.95918367,   8.36734694,   8.7755102 ,   9.18367347,
         9.59183673,  10.        ])

In [143]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [144]:
np.linspace(2,12)

array([ 2.        ,  2.20408163,  2.40816327,  2.6122449 ,  2.81632653,
        3.02040816,  3.2244898 ,  3.42857143,  3.63265306,  3.83673469,
        4.04081633,  4.24489796,  4.44897959,  4.65306122,  4.85714286,
        5.06122449,  5.26530612,  5.46938776,  5.67346939,  5.87755102,
        6.08163265,  6.28571429,  6.48979592,  6.69387755,  6.89795918,
        7.10204082,  7.30612245,  7.51020408,  7.71428571,  7.91836735,
        8.12244898,  8.32653061,  8.53061224,  8.73469388,  8.93877551,
        9.14285714,  9.34693878,  9.55102041,  9.75510204,  9.95918367,
       10.16326531, 10.36734694, 10.57142857, 10.7755102 , 10.97959184,
       11.18367347, 11.3877551 , 11.59183673, 11.79591837, 12.        ])

In [146]:
np.linspace(-2,12)

array([-2.        , -1.71428571, -1.42857143, -1.14285714, -0.85714286,
       -0.57142857, -0.28571429,  0.        ,  0.28571429,  0.57142857,
        0.85714286,  1.14285714,  1.42857143,  1.71428571,  2.        ,
        2.28571429,  2.57142857,  2.85714286,  3.14285714,  3.42857143,
        3.71428571,  4.        ,  4.28571429,  4.57142857,  4.85714286,
        5.14285714,  5.42857143,  5.71428571,  6.        ,  6.28571429,
        6.57142857,  6.85714286,  7.14285714,  7.42857143,  7.71428571,
        8.        ,  8.28571429,  8.57142857,  8.85714286,  9.14285714,
        9.42857143,  9.71428571, 10.        , 10.28571429, 10.57142857,
       10.85714286, 11.14285714, 11.42857143, 11.71428571, 12.        ])

In [149]:
np.linspace(-2,12,6)

array([-2. ,  0.8,  3.6,  6.4,  9.2, 12. ])

## identity

identity matrix is that diagnol items will be ones and everything will be zeros

In [152]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [154]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [156]:
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

## Array Attributes

In [159]:
a1=np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [160]:
a2=np.arange(12,dtype=float).reshape(3,4)
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [163]:
a3=np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [165]:
np.arange(8).reshape(2,2)

ValueError: cannot reshape array of size 8 into shape (2,2)

## ndim

to findout given arrays number of dimensions

In [168]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [170]:
a1.ndim

1

In [172]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [174]:
a2.ndim

2

In [176]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [178]:
a3.ndim

3

## shape

given each item consist of no. of rows and no. of column

In [181]:
a1.shape

(10,)

In [183]:
a2.shape

(3, 4)

In [185]:
a3.shape

(2, 2, 2)

## size

gives number of items

In [188]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [190]:
a3.size

8

In [192]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [194]:
a2.size

12

## item size

memory occupied by the item

In [197]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [199]:
a1.itemsize

4

In [201]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [203]:
a2.itemsize

8

In [205]:
a3.itemsize

4

## dtype

In [208]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


## change dtype

In [211]:
x=np.array([33,22,2.5])
x

array([33. , 22. ,  2.5])

In [213]:
x.astype(int)

array([33, 22,  2])

In [215]:
x.astype(bool)

array([ True,  True,  True])

In [217]:
x.astype(float)

array([33. , 22. ,  2.5])

In [219]:
x.astype(complex)

array([33. +0.j, 22. +0.j,  2.5+0.j])

## Array operations

In [222]:
z1=np.arange(12).reshape(3,4)
z2=np.arange(12,24).reshape(3,4)

In [224]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [226]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## scalar operations

scalar operations on Numpy arrays include performing additions or subtractions or multiplications on each element of a Numpy array.

In [230]:
z1+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [232]:
z1-2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [234]:
z1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [236]:
z1**2 #power 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [238]:
z1%2 #remainder

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]], dtype=int32)

## Relational operators

the relational operators are also known as comparison operators.
Thier main function is to return either a true or false based on the value of operands.

In [241]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [243]:
z2>2
# if 2 is greater than everything gives True

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [245]:
z2>20

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True]])

In [247]:
z2<2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [249]:
z2<20

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False, False, False, False]])

## vector operations

we can apply on both numpy array

In [252]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [254]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [256]:
z1+z2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [258]:
z1*z2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [260]:
z1-z2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [262]:
z1//z2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [264]:
z1/z2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

## array functions

In [267]:
k1=np.random.random((3,3))
k1=np.round(k1*100)
k1

array([[26., 64., 76.],
       [10., 46., 62.],
       [75., 92., 33.]])

In [269]:
np.max(k1)

92.0

In [271]:
np.min(k1)

10.0

In [273]:
np.sum(k1)

484.0

In [275]:
np.prod(k1)

# prod------> product of k1 (multiplication)

821257721856000.0

## in numpy

0 = column & 1 = row

In [278]:
# if we want maximum of every row

np.max(k1, axis=1)

array([76., 62., 92.])

In [280]:
# if we want maximum of every column

np.max(k1, axis=0)

array([75., 92., 76.])

In [282]:
np.min(k1, axis=1)

array([26., 10., 33.])

In [284]:
np.min(k1, axis=0)

array([10., 46., 33.])

In [286]:
np.prod(k1,axis=1)

array([126464.,  28520., 227700.])

## Statistics related functions

In [289]:
k1

array([[26., 64., 76.],
       [10., 46., 62.],
       [75., 92., 33.]])

In [291]:
np.mean(k1)

53.77777777777778

In [293]:
# mean of every column

k1.mean(axis=0)

array([37.        , 67.33333333, 57.        ])

In [295]:
k1.mean(axis=1)

array([55.33333333, 39.33333333, 66.66666667])

In [297]:
np.median(k1)

62.0

In [299]:
np.median(k1,axis=0)

array([26., 64., 62.])

In [301]:
np.median(k1,axis=1)

array([64., 46., 75.])

In [303]:
# STANDARD DEVIATION

np.std(k1)

25.292852647768466

In [305]:
np.std(k1,axis=0)

array([27.65260687, 18.92675942, 17.90716802])

In [307]:
# VARIANCE

np.var(k1)

639.7283950617284

## Trignometry Functions

In [310]:
np.sin(k1)

array([[ 0.76255845,  0.92002604,  0.56610764],
       [-0.54402111,  0.90178835, -0.7391807 ],
       [-0.38778164, -0.77946607,  0.99991186]])

In [312]:
np.tan(k1)

array([[  1.17875355,   2.34786031,   0.68674769],
       [  0.64836083,  -2.08661353,  -1.09750978],
       [ -0.42070095,   1.24427006, -75.3130148 ]])

## dot product

the numpy module of python provides a function to perform the dot product of 2 arrays.

In [315]:
s2=np.arange(12).reshape(3,4)
s3=np.arange(12,24).reshape(4,3)

In [317]:
s2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [319]:
s3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [321]:
np.dot(s2,s3)

#dot product of s2 & s3
# first row of s2 * first column of s3 (sum the product)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

## Log and Exponents

In [324]:
np.exp(s2)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

## round/floor/ceil

## 1. round

the numpy.round() function rounds the element of an array to the nearest integer or to the specified number of decimals.

In [330]:
arr=np.array([1.2, 2.7, 3.5, 4.9])
round_arr=np.round(arr)
print(round_arr)

[1. 3. 4. 5.]


In [332]:
arr=np.array([1.234, 2.567, 3.891])
round_arr=np.round(arr,decimals=2)
print(round_arr)

[1.23 2.57 3.89]


In [334]:
np.round(np.random.random((2,3))*100)

array([[19., 17., 60.],
       [92., 51., 53.]])

## 2. floor

the numpy.floor() function returns the largest integer less than or equal to each element of an array.

In [339]:
arr=np.array([1.2, 2.7, 3.5, 4.9])
floored_arr=np.floor(arr)
print(floored_arr)

[1. 2. 3. 4.]


In [341]:
np.floor(np.random.random((2,3))*100)

array([[24., 49., 11.],
       [31., 36., 27.]])

## 3. ceil

the numpy.ceil() function returns the smallest integer greater than or equal to each element of an array

In [345]:
arr=np.array([1.2, 2.7, 3.5, 4.9])
ceiled_arr=np.ceil(arr)
print(ceiled_arr)

[2. 3. 4. 5.]


In [347]:
np.ceil(np.random.random((2,3))*100)

array([[86., 84., 37.],
       [45., 57., 51.]])

## Indexing

In [350]:
p1=np.arange(10)
p2=np.arange(12).reshape(3,4)
p3=np.arange(8).reshape(2,2,2)

In [352]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [354]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [356]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

## Indexing on 1D array

In [359]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [361]:
p1[-1]

9

In [363]:
p1[0]

0

## Indexing on 2D array

In [366]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [370]:
p2[1,2]

6

In [372]:
p2[2,3]

11

In [374]:
p2[1,0]

4

In [376]:
p2[-1,-3]

9

In [378]:
p2[-2,3]

7

In [385]:
p2[1,0,1]

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

## Indexing on 3D array (Tensors)

In [381]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [383]:
p3[1,0,1]

5

In [387]:
p3[0,1,1]

3

In [389]:
p3[0,1,0]

2

In [391]:
p3[0,0,0]

0

In [393]:
p3[1,1,0]

6

## Slicing

## slicing on 1D array

In [398]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [400]:
p1[2:5]

array([2, 3, 4])

In [402]:
p1[2:5:2]

array([2, 4])

## slicing on 2D array

In [405]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [409]:
p2[0,:]

array([0, 1, 2, 3])

In [411]:
p2[:,2] 

array([ 2,  6, 10])

In [413]:
p2[1:3]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [415]:
p2[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [417]:
p2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [419]:
p2[::2]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [421]:
p2[1::2]

array([[4, 5, 6, 7]])

In [423]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [425]:
p2[1]

array([4, 5, 6, 7])

In [427]:
p2[1,::3]

array([4, 7])

In [429]:
p2[0:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [431]:
p2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [433]:
p2[0:2,1::2]

array([[1, 3],
       [5, 7]])

## slicing on 3D array

In [436]:
p3=np.arange(27).reshape(3,3,3)
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [438]:
p3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [440]:
p3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [442]:
p3[0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [444]:
p3[0,1:]

array([[3, 4, 5],
       [6, 7, 8]])

In [446]:
p3[1,:1]

array([[ 9, 10, 11]])

In [448]:
p3[1,:,1]

array([10, 13, 16])

In [450]:
p3[2]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [452]:
p3[2,1:]

array([[21, 22, 23],
       [24, 25, 26]])

In [454]:
p3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [458]:
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [462]:
p3[0::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [460]:
p3[0::2,0]

array([[ 0,  1,  2],
       [18, 19, 20]])

## Iterating

In [465]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### looping on 1D array

In [468]:
for i in p1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [470]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### looping on 2D array

In [473]:
for i in p2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [475]:
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

### looping on 3D array

In [478]:
for i in p3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


### 
print all items in 3D using nditer ----> first convert into 1D and apply loop

In [482]:
for i in np.nditer(p3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


## Reshaping

Transpose -----> Converts rows into columns and columns into rows

In [485]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [487]:
np.transpose(p2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [489]:
#Another method

p2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [491]:
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [493]:
p3.T

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

## Ravel

converting any dimensions to 1D

In [497]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [499]:
p2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [501]:
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [503]:
p3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

## Stacking

Stacking is the concept of joining arrays in numpy.  Arrays having the same dimensions can be stacked

In [509]:
#Horizontal stacking

w1=np.arange(12).reshape(3,4)
w2=np.arange(12,24).reshape(3,4)

In [511]:
w1 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [513]:
w2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#
using hstack for horizontal stacking

In [516]:
np.hstack((w1,w2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [518]:
# Vertical stacking

np.vstack((w1,w2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## Splitting

In [521]:
# Horizontal splitting

In [523]:
np.hsplit(w1,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [525]:
np.hsplit(w1,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [527]:
# Vertical spliting

In [531]:
w2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [535]:
np.vsplit(w2,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]