# 18 NOV

# NUMPY

### Create Numpy Ray

In [3]:
import numpy as np

In [5]:
np.__version__

'1.26.4'

### Creating Arrays

In [8]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [10]:
type(my_list)

list

In [12]:
arr=np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [14]:
type(arr)

numpy.ndarray

In [16]:
type(my_list)

list

### arange()

In [18]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [20]:
np.arange(3.0)

array([0., 1., 2.])

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [26]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [28]:
np.arange(20,10)

array([], dtype=int32)

In [30]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [32]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [34]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [36]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [38]:
np.arange(30,20)

array([], dtype=int32)

In [41]:
b=np.arange(-30,20)
b

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [43]:
np.arange(10,10)

array([], dtype=int32)

In [45]:
np.arange(-20,20)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,  18,
        19])

In [49]:
np.arange(10,30,5)
#starting from 10 to 30 with 5 step count

array([10, 15, 20, 25])

In [51]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [53]:
np.arange(10,30,5,1)

TypeError: Cannot interpret '1' as a data type

### zeros()

In [58]:
b1=np.zeros(2)
b1
#parameter tuning

array([0., 0.])

In [60]:
np.zeros(5,dtype=int) 
#hyperparameter tuning

array([0, 0, 0, 0, 0])

In [62]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [64]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [66]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [68]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [70]:
n=(5,7)
n1=(6,8)
print(np.zeros(n))
#parameter tuning
#print(np.zeros(n1,dtype=int) ##hyperparameter tunning

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [72]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [74]:
np.zeros(n,dtype=int)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

### ones

In [77]:
np.ones(4)

array([1., 1., 1., 1.])

In [79]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [81]:
n

(5, 7)

In [83]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [85]:
np.ones(n,dtype=int)

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [87]:
np.ones((5,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [89]:
np.twos(6)

AttributeError: module 'numpy' has no attribute 'twos'

In [91]:
np.twos(2,3)

AttributeError: module 'numpy' has no attribute 'twos'

In [93]:
np.three(2)

AttributeError: module 'numpy' has no attribute 'three'

In [95]:
np.three(2,3)

AttributeError: module 'numpy' has no attribute 'three'

In [97]:
from numpy import *

In [99]:
arange(3)

array([0, 1, 2])

In [101]:
range(12)
list(range(12))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [103]:
y=list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [105]:
rand(3,2)

NameError: name 'rand' is not defined

In [109]:
rand(3,2)
random.rand(3,2)

NameError: name 'rand' is not defined

In [111]:
random.rand(3,2)

array([[0.94123417, 0.79881851],
       [0.94135799, 0.75320512],
       [0.3228494 , 0.63807745]])

In [113]:
np.rand(3,2)

AttributeError: module 'numpy' has no attribute 'rand'

In [115]:
np.random.rand(4)

array([0.42032106, 0.97025822, 0.34443079, 0.4429568 ])

In [117]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [119]:
np.random.rand(2,4)

array([[0.94821904, 0.75612806, 0.24370298, 0.83434635],
       [0.55060184, 0.38148806, 0.7712612 , 0.07871078]])

In [121]:
np.random.randint(2,20)

11

In [123]:
np.random.randint(0,2)

0

In [125]:
np.random.randint(1,10,4)

array([9, 3, 2, 9])

In [129]:
np.random.randint(1,3,5)
# from 1 to 3 number pick 5 numbers

array([1, 1, 2, 2, 2])

In [131]:
np.random.randint(30,20,10)

ValueError: low >= high

In [133]:
np.random.randint(1)

0

In [135]:
np.random.randint(5,9)

7

In [137]:
np.random.randint(10,21,3)

array([13, 17, 14])

In [139]:
np.random.randint(1,12,10)

array([ 6, 11,  3, 10, 10,  9,  3,  8, 10, 11])

In [141]:
np.random.randint(10,40,(10,10))

array([[13, 37, 24, 30, 28, 19, 13, 34, 17, 10],
       [19, 21, 28, 25, 28, 38, 31, 17, 34, 36],
       [26, 24, 14, 27, 25, 16, 27, 19, 16, 19],
       [13, 14, 33, 31, 30, 35, 24, 35, 13, 15],
       [29, 28, 38, 24, 15, 21, 26, 28, 26, 30],
       [26, 21, 23, 29, 31, 20, 12, 21, 17, 17],
       [17, 20, 37, 19, 11, 28, 11, 32, 24, 28],
       [25, 30, 31, 31, 39, 23, 31, 38, 12, 39],
       [21, 15, 39, 28, 11, 31, 10, 12, 14, 34],
       [22, 36, 23, 29, 34, 27, 33, 18, 31, 38]])

In [143]:
b=np.random.randint(10,20,(5,4))
b

array([[15, 15, 18, 16],
       [12, 11, 13, 17],
       [15, 11, 15, 17],
       [17, 16, 11, 18],
       [10, 13, 13, 15]])

In [145]:
b[:]

array([[15, 15, 18, 16],
       [12, 11, 13, 17],
       [15, 11, 15, 17],
       [17, 16, 11, 18],
       [10, 13, 13, 15]])

In [149]:
b[0:2]
# n-1 formula that means 2-1=1 i.e., 1st row 

array([[15, 15, 18, 16],
       [12, 11, 13, 17]])

In [153]:
b[0:-1]
# indexing from 0 i.e., forward
# formula n-1 -1-1=-2 i.e., backward -2 row from back

array([[15, 15, 18, 16],
       [12, 11, 13, 17],
       [15, 11, 15, 17],
       [17, 16, 11, 18]])

In [155]:
b[0,2]
#index of 0 column 2 number

18

In [157]:
np.random.randint(10,20,(4,4))

array([[10, 14, 10, 18],
       [13, 15, 13, 10],
       [11, 15, 16, 19],
       [19, 16, 10, 12]])

### Operations

In [160]:
a=np.random.randint(10,20,5)
a

array([15, 17, 10, 19, 12])

In [162]:
arr

array([0, 1, 2, 3, 4, 5])

In [166]:
arr2=np.random.randint(0,100,(10,10))
arr2

array([[81, 68, 72, 70, 76, 98, 14, 98,  0,  4],
       [42, 91, 59, 94,  0, 90, 13, 97, 72, 77],
       [24, 26, 50, 86, 67, 15, 45,  4, 55, 66],
       [87, 91, 23, 70, 51, 88, 87, 68, 96, 22],
       [62,  7, 65, 25, 59,  4, 57, 51, 18, 31],
       [35, 42, 20, 68, 78,  9,  7, 13, 59, 60],
       [96, 26, 98, 31,  8, 50, 49, 55, 76,  0],
       [71, 39, 97, 95, 95, 98, 96,  4, 46, 71],
       [59, 53, 83, 37, 32, 13, 51, 60, 55, 36],
       [62,  9, 45, 96, 34, 44, 58, 92, 65, 79]])

In [168]:
arr

array([0, 1, 2, 3, 4, 5])

In [170]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [172]:
arr[:4]

array([0, 1, 2, 3])

In [176]:
arr2[:]

array([[81, 68, 72, 70, 76, 98, 14, 98,  0,  4],
       [42, 91, 59, 94,  0, 90, 13, 97, 72, 77],
       [24, 26, 50, 86, 67, 15, 45,  4, 55, 66],
       [87, 91, 23, 70, 51, 88, 87, 68, 96, 22],
       [62,  7, 65, 25, 59,  4, 57, 51, 18, 31],
       [35, 42, 20, 68, 78,  9,  7, 13, 59, 60],
       [96, 26, 98, 31,  8, 50, 49, 55, 76,  0],
       [71, 39, 97, 95, 95, 98, 96,  4, 46, 71],
       [59, 53, 83, 37, 32, 13, 51, 60, 55, 36],
       [62,  9, 45, 96, 34, 44, 58, 92, 65, 79]])

In [178]:
arr2[0:5]

array([[81, 68, 72, 70, 76, 98, 14, 98,  0,  4],
       [42, 91, 59, 94,  0, 90, 13, 97, 72, 77],
       [24, 26, 50, 86, 67, 15, 45,  4, 55, 66],
       [87, 91, 23, 70, 51, 88, 87, 68, 96, 22],
       [62,  7, 65, 25, 59,  4, 57, 51, 18, 31]])

In [180]:
arr2[1,5]

90

In [184]:
arr2

array([[81, 68, 72, 70, 76, 98, 14, 98,  0,  4],
       [42, 91, 59, 94,  0, 90, 13, 97, 72, 77],
       [24, 26, 50, 86, 67, 15, 45,  4, 55, 66],
       [87, 91, 23, 70, 51, 88, 87, 68, 96, 22],
       [62,  7, 65, 25, 59,  4, 57, 51, 18, 31],
       [35, 42, 20, 68, 78,  9,  7, 13, 59, 60],
       [96, 26, 98, 31,  8, 50, 49, 55, 76,  0],
       [71, 39, 97, 95, 95, 98, 96,  4, 46, 71],
       [59, 53, 83, 37, 32, 13, 51, 60, 55, 36],
       [62,  9, 45, 96, 34, 44, 58, 92, 65, 79]])

In [186]:
arr2[-5:5]

array([], shape=(0, 10), dtype=int32)

In [188]:
arr2[-5,5]

9

In [190]:
arr2[-5,-5]

9

In [192]:
arr2[::-1]

array([[62,  9, 45, 96, 34, 44, 58, 92, 65, 79],
       [59, 53, 83, 37, 32, 13, 51, 60, 55, 36],
       [71, 39, 97, 95, 95, 98, 96,  4, 46, 71],
       [96, 26, 98, 31,  8, 50, 49, 55, 76,  0],
       [35, 42, 20, 68, 78,  9,  7, 13, 59, 60],
       [62,  7, 65, 25, 59,  4, 57, 51, 18, 31],
       [87, 91, 23, 70, 51, 88, 87, 68, 96, 22],
       [24, 26, 50, 86, 67, 15, 45,  4, 55, 66],
       [42, 91, 59, 94,  0, 90, 13, 97, 72, 77],
       [81, 68, 72, 70, 76, 98, 14, 98,  0,  4]])

In [200]:
arr2[::-2]
#step count 0f 2

array([[62,  9, 45, 96, 34, 44, 58, 92, 65, 79],
       [71, 39, 97, 95, 95, 98, 96,  4, 46, 71],
       [35, 42, 20, 68, 78,  9,  7, 13, 59, 60],
       [87, 91, 23, 70, 51, 88, 87, 68, 96, 22],
       [42, 91, 59, 94,  0, 90, 13, 97, 72, 77]])

In [202]:
arr2[::-3]

array([[62,  9, 45, 96, 34, 44, 58, 92, 65, 79],
       [96, 26, 98, 31,  8, 50, 49, 55, 76,  0],
       [87, 91, 23, 70, 51, 88, 87, 68, 96, 22],
       [81, 68, 72, 70, 76, 98, 14, 98,  0,  4]])

In [204]:
arr

array([0, 1, 2, 3, 4, 5])

In [206]:
arr.max()

5

In [208]:
arr.min()

0

In [210]:
arr.mean()

2.5

In [212]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [216]:
from numpy import *
a=array([1,2,3,4,9])
median(a)

3.0

In [218]:
arr

array([0, 1, 2, 3, 4, 5])

In [220]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [222]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [224]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [226]:
arr.reshape(1,5)

ValueError: cannot reshape array of size 6 into shape (1,5)

In [230]:
arr.reshape(3,2,order='C')

array([[0, 1],
       [2, 3],
       [4, 5]])

In [234]:
arr.reshape(3,2,order='F')

array([[0, 3],
       [1, 4],
       [2, 5]])

In [236]:
arr.reshape(3,2,order='A')

array([[0, 1],
       [2, 3],
       [4, 5]])

In [238]:
arr.reshape(3,2,order='K')

ValueError: order 'K' is not permitted for reshaping

In [240]:
arr

array([0, 1, 2, 3, 4, 5])

In [242]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [244]:
arr.reshape(1,4)

ValueError: cannot reshape array of size 6 into shape (1,4)

In [246]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [248]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [250]:
arr.reshape(2,6)

ValueError: cannot reshape array of size 6 into shape (2,6)

In [252]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

### Indexing

In [5]:
import numpy as np

In [7]:
mat=np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [9]:
row=4
col=5

In [11]:
col

5

In [13]:
row

4

In [15]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [19]:
mat[row,col]
# 4th index row and 5th index column comman digit

45

In [23]:
mat[4,5]

45

In [25]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [27]:
col=6

In [29]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [33]:
#with slicing
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [37]:
mat[4,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [39]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [41]:
row

4

In [43]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [45]:
mat[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [47]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [49]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [53]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [55]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [57]:
mat[1,4]

14

In [59]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [61]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [63]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [67]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [69]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [72]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [74]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [76]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [78]:
mat[0:10:3]
#with 3 step count

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [80]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [84]:
mat[::-2]
#with 2 step counting from backward

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [86]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [88]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [90]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [92]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [94]:
mat[1,6]

16

In [96]:
mat[1:2,2:4]

array([[12, 13]])

In [98]:
mat[2:3,2:3]

array([[22]])

In [100]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

In [102]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [104]:
mat[2:3,4:5]

array([[24]])

### Masking

In [107]:
mat
#we also called as filter

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [109]:
id(mat)

1782586435664

In [111]:
mat<50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [113]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [115]:
mat==50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [117]:
mat[mat==50]

array([50])

In [119]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [121]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [123]:
mat[mat>=50]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [125]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])